---
- name: Pulling OpenSM container image
  kayobe_container_image:
    name: "{{ item.value.image }}"
    source: pull
    state: present
  with_dict: "{{ opensm_services }}"
  when:
    - item.value.enabled
    - opensm_action != 'destroy'
  become: "{{ container_engine == 'podman' }}"
