---
- src: ahuffman.resolv
  version: 1.3.1
- src: jriguera.configdrive
  # There are no versioned releases of this role.
  version: 56daf0017783bd4fa5722da4ee91b66ddd4e6b6a
- src: MichaelRigart.interfaces
  version: v1.9.2
- src: mrlesmithjr.manage_lvm
  version: v0.1.4
- src: mrlesmithjr.mdadm
  version: v0.1.0
- src: mrlesmithjr.chrony
  version: v0.1.0
- src: singleplatform-eng.users
  version: v1.2.5
- src: stackhpc.dell-powerconnect-switch
  version: v1.1.0
- src: stackhpc.drac
  version: 1.1.5
- src: stackhpc.drac-facts
  version: 1.0.0
- src: stackhpc.grafana-conf
  version: 1.1.0
- src: https://github.com/stackhpc/ansible-role-libvirt-host
  name: stackhpc.libvirt-host
  version: stackhpc/backports/ansible-2.8
- src: stackhpc.libvirt-vm
  version: v1.13.0
- src: stackhpc.mellanox-switch
  version: v1.0.0
- src: stackhpc.os-images
  version: v1.10.5
- src: stackhpc.os-ironic-state
  version: v1.3.1
- src: stackhpc.os-networks
  version: v1.4.0
- src: stackhpc.os-openstackclient
  version: v1.4.0
- src: stackhpc.os_openstacksdk
  version: v1.0.0
- src: yatesr.timezone
  version: 1.2.0
