---
- name: Ensure docker registry container is stopped
  docker_container:
    name: "{{ item.value.container_name }}"
    state: "absent"
  with_dict: "{{ docker_registry_services }}"

- name: Check whether docker registry volumes are present
  command: docker volume inspect {{ volume }}
  changed_when: False
  with_subelements:
    - "{{ docker_registry_services }}"
    - volumes
  when: "'/' not in volume"
  failed_when:
    - volume_result.rc != 0
    - "'no such volume' not in volume_result.stderr | lower"
  vars:
    volume: "{{ item.1.split(':')[0] }}"
  register: volume_result

- name: Ensure docker registry volumes are absent
  command: docker volume rm {{ volume }}
  with_items: "{{ volume_result.results }}"
  when:
    - item is not skipped
    - item.rc == 0
  vars:
    volume: "{{ item.item.1.split(':')[0] }}"
