---
- name: Pulling Docker registry container image
  kayobe_container_image:
    name: "{{ item.value.image }}"
    source: pull
    state: present
  with_dict: "{{ docker_registry_services }}"
  when:
    - item.value.enabled
    - docker_registry_action != 'destroy'
  become: "{{ container_engine == 'podman' }}"
