---
- name: Restart inspection store container
  kayobe_container:
    name: "{{ item.value.container_name }}"
    state: started
    restart: True
    # NOTE: The image argument shouldn't be required, but without it this
    # handler fails on Ansible 2.3. Related bug:
    # https://github.com/ansible/ansible/issues/21188.
    image: "{{ item.value.image }}"
  with_dict: "{{ inspection_store_services }}"
  when: item.value.enabled
  become: "{{ container_engine == 'podman' }}"

- name: Ensure inspection store data directory exists
  command: >
    {{ container_engine }} exec {{ inspection_store_services.inspection_store.container_name }}
    bash -c "mkdir -p /data/ironic-inspector &&
             chown nginx:nginx /data/ironic-inspector"
  when: inspection_store_services.inspection_store.enabled
  become: "{{ container_engine == 'podman' }}"
