---
# Roughly follows kolla-ansible's service deployment patterns.

# Action to perform. One of 'deploy', 'destroy', 'pull', 'reconfigure',
# 'stop', 'upgrade'.
opensm_action: deploy

# Whether OpenSM is enabled.
opensm_enabled: true

# Service deployment definition.
opensm_services:
  opensm:
    container_name: opensm
    enabled: "{{ opensm_enabled }}"
    image: "{{ opensm_image_full }}"
    privileged: True
    read_only: True
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "opensm_cache:/var/cache/opensm"
      - "opensm_logs:/var/log"

####################
# Docker
####################
opensm_namespace: "jumanjiman"
opensm_image: "{{ docker_registry ~ '/' if docker_registry | default else 'docker.io/' }}{{ opensm_namespace }}/opensm"
opensm_tag: "latest"
opensm_image_full: "{{ opensm_image }}:{{ opensm_tag }}"

opensm_restart_policy: "unless-stopped"
#opensm_restart_retries:
