---
- name: Ensure introspection rules exist
  vars:
    ansible_python_interpreter: "{{ ironic_inspector_venv }}/bin/python"
  os_ironic_inspector_rule:
    auth_type: "{{ ironic_inspector_auth_type }}"
    auth: "{{ ironic_inspector_auth }}"
    cacert: "{{ ironic_inspector_cacert | default(omit, true) }}"
    cloud: "{{ ironic_inspector_cloud | default(omit, true) }}"
    interface: "{{ ironic_inspector_interface | default(omit, true) }}"
    conditions: "{{ item.conditions }}"
    actions: "{{ item.actions }}"
    description: "{{ item.description | default(omit) }}"
    uuid: "{{ item.uuid | default(item.description | to_uuid) | default(omit) }}"
    state: present
  with_items: "{{ ironic_inspector_rules }}"
