# Copyright (c) 2024 StackHPC Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from dataclasses import dataclass
from dataclasses import field
import json
from typing import List


@dataclass
class Stats(object):
    """Kayobe Ansible statistics.

    This class represents the statistics generated by the kayobe_stats callback
    plugin, and needs to be kept in sync with it.
    """

    num_failures: int = 0
    num_unreachable: int = 0
    failures: List[str] = field(default_factory=list)
    unreachable: List[str] = field(default_factory=list)
    no_hosts_remaining: bool = False

    @classmethod
    def from_json(cls, json_path: str):
        """Construct a Stats object from statistics in a JSON file."""
        with open(json_path) as f:
            return cls(**json.load(f))

    def completed_without_failures(self) -> bool:
        """Return whether execution continued to completion without failures.

        Unreachable hosts are not counted as failures in this context.
        """
        return self.num_failures == 0 and not self.no_hosts_remaining
