---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/collections.yml
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: centos-stream9
    image: quay.io/centos/centos:stream9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
