---
- name: Pulling inspection store container image
  kayobe_container_image:
    name: "{{ item.value.image }}"
    source: pull
    state: present
  with_dict: "{{ inspection_store_services }}"
  when:
    - item.value.enabled
    - inspection_store_action != 'destroy'
  become: "{{ container_engine == 'podman' }}"
