---

- name: Register baremetal compute nodes
  hosts: controllers[0]
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
  tasks:
    - name: Set up openstack cli virtualenv
      pip:
        virtualenv: "{{ venv }}"
        name:
          - python-openstackclient
          - python-ironicclient
        state: latest
        virtualenv_command: "python3.{{ ansible_facts.python.version.minor }} -m venv"
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"

- name: Ensure baremetal compute nodes are registered in ironic
  hosts: baremetal-compute
  gather_facts: false
  max_fail_percentage: >-
    {{ baremetal_compute_register_max_fail_percentage |
       default(baremetal_compute_max_fail_percentage) |
       default(kayobe_max_fail_percentage) |
       default(100) }}
  tags:
    - baremetal
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
    controller_host: "{{ groups['controllers'][0] }}"
  tasks:
    - name: Enroll baremetal nodes in Ironic
      openstack.cloud.baremetal_node:
        auth_type: "{{ openstack_auth_type }}"
        auth: "{{ openstack_auth }}"
        bios_interface: "{{ baremetal_compute_bios_interface }}"
        boot_interface: "{{ baremetal_compute_boot_interface }}"
        ca_cert: "{{ openstack_cacert | default(omit, true) }}"
        chassis_id: "{{ baremetal_compute_chassis_id }}"
        console_interface: "{{ baremetal_compute_console_interface }}"
        deploy_interface: "{{ baremetal_compute_deploy_interface }}"
        driver: "{{ baremetal_compute_driver }}"
        driver_info: "{{ baremetal_compute_driver_info }}"
        id: "{{ baremetal_compute_uuid }}"
        inspect_interface: "{{ baremetal_compute_inspect_interface }}"
        interface: "{{ openstack_interface | default(omit, true) }}"
        management_interface: "{{ baremetal_compute_management_interface }}"
        name: "{{ inventory_hostname }}"
        # NOTE(jake): We need to add network_data to this module!
        network_interface: "{{ baremetal_compute_network_interface }}"
        nics: "{{ baremetal_compute_nics }}"
        power_interface: "{{ baremetal_compute_power_interface }}"
        properties: "{{ baremetal_compute_properties }}"
        provision_state: "{{ baremetal_compute_provision_state }}"
        raid_interface: "{{ baremetal_compute_raid_interface }}"
        rescue_interface: "{{ baremetal_compute_rescue_interface }}"
        resource_class: "{{ baremetal_compute_resource_class }}"
        state: "{{ 'absent' if baremetal_compute_delete_nodes else 'present' }}"
        storage_interface: "{{ baremetal_compute_storage_interface }}"
        timeout: "{{ baremetal_compute_timeout }}"
        vendor_interface: "{{ baremetal_compute_vendor_interface }}"
        wait: "{{ baremetal_compute_wait }}"
      delegate_to: "{{ controller_host }}"
      vars:
        # NOTE: Without this, the controller's ansible_host variable will not
        # be respected when using delegate_to.
        ansible_host: "{{ hostvars[controller_host].ansible_host | default(controller_host) }}"
        ansible_python_interpreter: "{{ venv }}/bin/python3"
