---
- project:
    check:
      jobs:
        - kayobe-overcloud-centos
        - kayobe-overcloud-centos8

    gate:
      queue: kayobe
      jobs:
        - kayobe-tox-ansible-syntax
        - kayobe-tox-ansible
        - kayobe-tox-molecule
        - kayobe-overcloud-centos
        - kayobe-overcloud-centos8
        - kayobe-overcloud-upgrade-centos
        - kayobe-seed-centos
        - kayobe-seed-upgrade-centos
