---
- name: Login to docker registry
  docker_login:
    registry_url: "{{ kolla_docker_registry or omit }}"
    username: "{{ kolla_docker_registry_username }}"
    password: "{{ kolla_docker_registry_password }}"
    reauthorize: yes
  when:
    - kolla_docker_registry_username is truthy
    - kolla_docker_registry_password is truthy

- name: Deploy containers (loop)
  include_tasks: deploy.yml
  vars:
    container_name: "{{ item.key }}"
    container_config: "{{ item.value }}"
  with_dict: "{{ seed_containers }}"
